![](https://itlab1024-1256529903.cos.ap-beijing.myqcloud.com/202207281322806.png)

# 介绍

Go中的错误很简单，函数会有另外一个error返回值，在调用函数的时候，可以先判断是否有错误。Go内置的错误就叫做error。

接下来看看如何使用。

# 使用New方法

go的error提供了new方法创建一个错误

```go
package main

import (
	"errors"
	"fmt"
	"log"
)

func main() {
	i := 1
	j := 0
	i2, err := division(i, j)
	if err != nil {
		log.Fatal(err) // 不能为0
		return
	}
	fmt.Println(i2)
}

func division(i int, j int) (int, error) {
	if j == 0 {
		return 0, errors.New("不能为0")
	}
	return i / j, nil
}
```

# 使用fmt包下的Errorf方法

```go
func division(i int, j int) (int, error) {
	if j == 0 {
		//return 0, errors.New("不能为0")
		return 0, fmt.Errorf("不能为%d", j)
	}
	return i / j, nil
}
```

# 自定义错误

通过自定义个结构体，来自定义一种错误，比如定义一个名字不能为空的错误

自定义错误需要实现error接口(go中实现接口有点不好看出来，反正我目前不知道如何能快速看出来，因为他没有明确标记，实现了接口的所有函数，就认为实现了接口。否则认为没实现，不像Java那样使用implement关键字清晰明了)

```go
package main

import (
	"fmt"
	"log"
)

func main() {
	i := 1
	j := 1
	i2, err := division(i, j)
	if err != nil {
		log.Fatal(err) // 不能为0
		return
	}
	fmt.Println(i2)

	// 自定义错误的使用
	name := ""
	r, err := NameCheck(name)
	if err != nil {
		log.Fatal(err) // Name不能为
		return
	}
	fmt.Println(r)
}

func division(i int, j int) (int, error) {
	if j == 0 {
		//return 0, errors.New("不能为0")
		return 0, fmt.Errorf("不能为%d", j)
	}
	return i / j, nil
}

// NameEmptyError 自定义错误
type NameEmptyError struct {
	Name string
}

func (e *NameEmptyError) Error() string {
	return "Name不能为空"
}

func NameCheck(name string) (bool, error) {
	if name == "" {
		return false, &NameEmptyError{name}
	}
	return true, nil
}
```

